language: R
sudo: false
cache: packages
warnings_are_errors: false
r:
- release
before_install:
- openssl aes-256-cbc -K $encrypted_f08928906bbd_key -iv $encrypted_f08928906bbd_iv
  -in tests/testthat/credentials.rds.enc -out tests/testthat/credentials.rds -d
